Poll_Application/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('Polls/', include('Polls.urls')),
    path('admin/', admin.site.urls),
]

Polls/urls.py
from django.urls import path
from . import views
app_name = 'Polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(),name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:ques_id>/vote/', views.vote, name='vote'),
]

Polls/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here
#Two models question and choice represented as classes.
class Question(models.Model):
    ques_txt=models.CharField(max_length=200)
    pub_date=models.DateTimeField('Date of Publication')
    def __str__(self):
        return self.ques_txt
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    ques = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_txt = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_txt

Polls/views.py
from django.shortcuts import get_object_or_404, render
from .models import Question, Choice
from django.template import loader
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'Polls/index.html'
    context_object_name = 'recently_added_ques'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'Polls/details.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'Polls/results.html'

def vote(request, ques_id):
    question = get_object_or_404(Question, pk=ques_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'Polls/details.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('Polls:results', args=(question.id,)))

Polls/templates/Polls/details.html
<form action="{% url 'Polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.ques_txt }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_txt }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

Polls/templates/Polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'Polls/style.css' %}">

{% if recently_added_ques %}
    <ul>
    {% for question in recently_added_ques %}
    <li><a href="{% url 'Polls:detail' question.id %}">{{ question.ques_txt }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

Polls/templates/Polls/results.html
<h1>{{ question.ques_txt }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_txt }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'Polls:detail' question.id %}">Vote again?</a>